services:
  signindemo.api:
    image: signindemo.api
    build:
      context: .
      dockerfile: src/Api/SignInDemo.Api/Dockerfile
      
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      - MSSQL_SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_TCP_PORT=1433
    volumes:
      - ./sql_server/data:/var/opt/mssql/data
      - ./sql_server/log:/var/opt/mssql/log
      - ./sql_server/secrets:/var/opt/mssql/secrets
    ports:
      - "1433:1433"
